### ISSUE TITLE
Adding urls via helm chart

### ISSUE THREAD

**Issue by nishadsalam** [dirsigler/uptime-kuma-helm#107]
Hello,

How I can add the  monitoring url's through helm chart so it is easy to  manage the urls  in the chart. So each time we can recreate on the fly.  I have checked the

**Comment by dirsigler** [comment]
Hey @nishadsalam 
your sentence cut off on the end, so it is not really clear on what you wanted to say.

As far as I understand your question:
You would like to specify for example in the `values.yaml` your list of URLs which automatically get set-up in Uptime-Kuma whenever you install the Helm Chart in your system?

This is not possible within the Helm Chart itself and I am not familiar with such a feature with the uptime-kuma application itself.
