### ISSUE TITLE
Helm chart certificate not trusted

### ISSUE THREAD

**Issue by tommy31** [dirsigler/uptime-kuma-helm#113]
Hello, i was looking to test your chart helm but following the deployment i got one error:

`helm repo add uptime-kuma https://helm.irsigler.cloud
Error: looks like "https://helm.irsigler.cloud" is not a valid chart repository or cannot be reached: Get "https://helm.irsigler.cloud/index.yaml": x509: “helm.irsigler.cloud” certificate is not trusted`

**Comment by si458** [comment]
certificate seems ok now
you can also use the github repo for the chart
`helm repo add uptime-kuma https://dirsigler.github.io/uptime-kuma-helm`

**Comment by dirsigler** [comment]
Yeah seems like GitHub did some kind of change on their side which caused connectivity issues for some.
Issue is resolved for now.

**Comment by gergokee** [comment]
hi i have this exact same issue:
`Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm repo add https:--dirsigler.github.io-uptime-kuma-helm https://dirsigler.github.io/uptime-kuma-helm` failed exit status 1: Error: looks like "https://dirsigler.github.io/uptime-kuma-helm" is not a valid chart repository or cannot be reached: Get "https://helm.irsigler.cloud/index.yaml": tls: failed to verify certificate: x509: certificate signed by unknown authority`
