### ISSUE TITLE
HELM CHART FEATURE ENHANCEMENT

### ISSUE THREAD

**Issue by druheendas** [dirsigler/uptime-kuma-helm#132]
Can we add a feature in the helm chart, to use an existing secret, as to use this helm chart I will have to commit the API key in the values file of helm chart and push it to the VCS. I prefer using sealed secrets to encrypt secrets before pushing it to VCS.

**Comment by dirsigler** [comment]
Hey @druheendas ,

to be honest I am not quite understanding what your need is.
For what you do use the API Key?

If you have some API Keys or Secrets which you want to secure in your VCS I would recommend to use [Mozillas SOPS](https://github.com/getsops/sops). This way you can use the KMS system of your choice or GPG to encrypt the `values.yaml`.

Hope that helps you out!
