### ISSUE TITLE
helm.irsigler.cloud seems down

### ISSUE THREAD

**Issue by micedre** [dirsigler/uptime-kuma-helm#163]
Hi,

The helm chart repository at helm.irsigler.cloud seems down. There seems to be no dns entry for it.
It worked fine on May 14th (last time our argo-cd synced).

Thanks.

**Comment by yenda23** [comment]
I was working on Fri 2024-05-31...

**Comment by LeoFVO** [comment]
This is down for me too, maybe instable dns..

**Comment by dirsigler** [comment]
Hey, my bad.
Had to migrate the DNS zone.

Should be available now again.

**Comment by micedre** [comment]
Can confirm, thanks a lot :)
