### ISSUE TITLE
tag 1.23.11-debian is not available anymore

### ISSUE THREAD

**Issue by openJT** [dirsigler/uptime-kuma-helm#164]
Like the tile says! There is a 1.23.13-debian a 1.23.12-debian and a 1.23.10-debian but the 1.23.11-debian is gone!
Source: https://hub.docker.com/r/louislam/uptime-kuma/tags

**Comment by dirsigler** [comment]
Hey,

I don't manage the Docker Image you mentioned, therefore I am not able to help you with the issues on the missing image.
You might want to raise an issue on the official project page here: https://github.com/louislam/uptime-kuma/issues

Please let me know if I misunderstood your issue...
