### ISSUE TITLE
The tag: "1.23.11-debian" does not exist anymore.

### ISSUE THREAD

**Issue by MrHaroldA** [dirsigler/uptime-kuma-helm#165]
Missing the 1.23.11 Debian image: https://hub.docker.com/r/louislam/uptime-kuma/tags?page=&page_size=&ordering=&name=1.23.11

> Failed to pull image "louislam/uptime-kuma:1.23.11-debian": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/louislam/uptime-kuma:1.23.11-debian": failed to resolve reference "docker.io/louislam/uptime-kuma:1.23.11-debian": docker.io/louislam/uptime-kuma:1.23.11-debian: not found

The current image is 1.23.13: https://hub.docker.com/layers/louislam/uptime-kuma/1.23.13-debian/images/sha256-5ed40a58b56b689ec2af50230e8d28804503351fed5eb54b1aefe530a8ea1fdc?context=explore

**Comment by dirsigler** [comment]
Thats a duplicate to #164 .

I don't manage the Docker Image you mentioned, therefore I am not able to help you with the issues on the missing image.
You might want to raise an issue on the official project page here: https://github.com/louislam/uptime-kuma/issues

Please let me know if I misunderstood your issue...

**Comment by MrHaroldA** [comment]
> Please let me know if I misunderstood your issue...
Well, you cannot install the chart without specifying a custom image tag because the default tag does not exist anymore.

**Comment by dirsigler** [comment]
I see.
Updated the image, should be available now with the newest release.
