### ISSUE TITLE
Liveness probe failing since `2.19.0`

### ISSUE THREAD

**Issue by 9numbernine9** [dirsigler/uptime-kuma-helm#168]
Hello!

After upgrading from Helm chart `2.18.1` to `2.19.0`, it seems that the liveness probe is no longer working. The pod now shows the following events:

```
55s (x4 over 2m59s)    Normal    Started                  Pod/uptime-kuma-85c9bcbf8f-m2z84        Started container uptime-kuma
55s (x4 over 2m59s)    Normal    Created                  Pod/uptime-kuma-85c9bcbf8f-m2z84        Created container uptime-kuma
55s (x4 over 3m)       Normal    Pulled                   Pod/uptime-kuma-85c9bcbf8f-m2z84        Container image "louislam/uptime-kuma:1.23.13-debian" already present on machine
40s (x10 over 2m40s)   Warning   Unhealthy                Pod/uptime-kuma-85c9bcbf8f-m2z84        Liveness probe failed: /app/extra/healthcheck:1
ELF
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.20.2
```
I think this is a result of the changes made in PR #166 which added `node` as part of the command to execute for the liveness probe. I think the problem with this change is that `extra/healthcheck` is a compiled ELF executable, and `node` can't invoke a compiled binary (hence the `ELF` statement and `Invalid or unexpected token` error).

Steps to reproduce:
- `helm repo add uptime-kuma https://helm.irsigler.cloud`
- `helm upgrade uptime-kuma uptime-kuma/uptime-kuma --install --namespace uptime-kuma --create-namespace`

This error occurs in my environment (EKS, Kubernetes `1.28.8`) without any `values.yaml` specified. 

Workarounds for now:
- Revert to `2.18.1`
- Edit the `Deployment` to remove the `node` command from the `livenessProbe`.

**Comment by dirsigler** [comment]
Interesting issue. It seems I am moving forth and back with the livenessProbe configuration.
For some versions it works perfectly fine with the `node`, then it fails again.

At this point I am thinking about just removing the livenessProbe completely by default, assuming the application works perfectly fine.

**Comment by dirsigler** [comment]
Hey @9numbernine9 ,

by any chance you are setting anything for the LivenessProbe durations which are not the default values?

**Comment by dirsigler** [comment]
Hey @9numbernine9 ,

indeed there were some issues with the livenessProbe which were introduced before (see #166 ).
These changes were reverted. Additionally I added support to configure your own livenessProbe and readinessProbe as desired in the `values.yaml` (as [described here](https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/values.yaml#L109-L137) ).

**Comment by dirsigler** [comment]
Please let me know if you still encounter any issues.

**Comment by 9numbernine9** [comment]
Thanks @dirsigler ! Sorry for not responding sooner. I just tried the `2.19.1` release and it works great for me - I think reverting back to the original liveness probe _and_ making it configurable for other circumstances is a good solution. 👍

**Comment by dirsigler** [comment]
Glad to hear that it works now. Have a nice weekend!
