### ISSUE TITLE
ServiceMonitor has Unauthorized error with auth enabled

### ISSUE THREAD

**Issue by urbaman** [dirsigler/uptime-kuma-helm#180]
Hi,

How to set the servicemonitor from the chart to get to the metrics? Is basicauth needed? Is the chart enabling that?

Thank you.

**Comment by urbaman** [comment]
Ok solved, saw the basicAuth in the values, could be worth mentioning it in the readme.

**Comment by dirsigler** [comment]
It's an open source project. I am happy to review any PR with the changes proposed.

**Comment by antonengelhardt** [comment]
If there is always basic auth required to access uptime kuma and the metrics, then the basic auth values should be required/validated, but obv only if the service monitor is turned on. 

Secondly - and i dont know if thats possible - but if service monitor is enabled, there could be an option (for example `auto-provision` or `auto-setup`) which launches a job that creates the api credential, stores it in a secret, and uses that for auth.
