### ISSUE TITLE
Create ServiceMonitor and Secret for Prometheus metrics endpoint

### ISSUE THREAD

**Issue by dirsigler** [dirsigler/uptime-kuma-helm#58]
The upstream project provides some [basic Prometheus metrics](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration) which can be scrapped by Prometheus.

I am currently deepen my Prometheus knowledge and found a suitable solution which allows to scrape the Uptime-Kuma metrics.
The additions would be manifests of type:
- Secret to store the basic auth credentials
- ServiceMonitor to scrape the Service for metrics

Reference: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/basic-auth.md#basic-auth-for-targets

The Prometheus instance and Prometheus CRD configuration needs to be provided by the users of this Helm Chart.

**Comment by druheendas** [comment]
Can we add a feature in the helm chart, to use an existing secret, as to use this helm chart I will have to commit the API key in the values file of helm chart and push it to the VCS. We prefer using sealed secrets to encrypt secrets before pushing it to VCS.
