### ISSUE TITLE
Alpine image is deprecated

### ISSUE THREAD

**Issue by dels78** [dirsigler/uptime-kuma-helm#85]
see https://github.com/louislam/uptime-kuma/issues/2463

As of 3 weeks ago, louislam has deprecated the alpine image due to dns issues and recommends the debian based one, which the latest of is "1.19.4-debian"

I tried to submit a PR for the change but couldn't push so I figured this would help!

Thanks

**Comment by dirsigler** [comment]
Ohh did not see that (need to work on my upstream notifications anyway) so thank you very much for raising this issue!

Will create a change later, even tho I hate having now a bigger image 😅
